- name: Install required packages
  yum:
    name: "{{item}}"
    state: latest
  loop:
    - python
    - python-pip
    - python-devel
    - gcc

- name: Install tower-cli
  pip:
    name: ansible-tower-cli
    state: latest

- name: Configure the tower cli file
  template: 
    src: tower_cli.j2
    dest: "~/.tower_cli.cfg"
    mode: 0600

- name: Append file
  lineinfile:
    path: /root/license.txt
    insertbefore: '"company_name.*"'
    line: '“eula_accepted” : "true",'

- name: Generate var file for order_svc.sh script
  template:
    src: aws_jq_vars.yml
    dest: /tmp/aws_jq_vars.yml

- name: Generate var file for tower module
  template:
    src: tower_info.yml
    dest: /tmp/tower_info.yml

- name: Copy opentlc ssh keys
  copy:
    src: "{{path_to_opentlc_key}}"
    dest: /root/secret.pem

- name: Copy AWS read only creds
  copy:
    src: inventory_vars.json
    dest: /root/inventory_vars.json

- name: Copy inventory vars
  copy:
    src: inventory_vars.json
    dest: /root/inventory_vars.json
